# Generated by Django 3.2.19 on 2026-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20260208_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
